# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: udp_packet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import player_pb2 as player__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='udp_packet.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('\n\005protoB\017UdpPacketProtos'),
  serialized_pb=_b('\n\x10udp_packet.proto\x1a\x0cplayer.proto\"\xab\x04\n\tUdpPacket\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.UdpPacket.PacketType\x1aV\n\nDrawPacket\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.UdpPacket.PacketType\x12\t\n\x01x\x18\x02 \x02(\x05\x12\t\n\x01y\x18\x03 \x02(\x05\x12\r\n\x05\x63olor\x18\x04 \x02(\t\x1aL\n\x0cWinnerPacket\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.UdpPacket.PacketType\x12\x17\n\x06player\x18\x02 \x02(\x0b\x32\x07.Player\x1a\x34\n\rTimeoutPacket\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.UdpPacket.PacketType\x1aZ\n\nTurnPacket\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.UdpPacket.PacketType\x12\x17\n\x06player\x18\x02 \x02(\x0b\x32\x07.Player\x12\x0e\n\x06object\x18\x03 \x01(\t\x1a?\n\nTimePacket\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.UdpPacket.PacketType\x12\x0c\n\x04time\x18\x02 \x02(\x05\x1a\x31\n\nPortPacket\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.UdpPacket.PacketType\"M\n\nPacketType\x12\x08\n\x04\x44RAW\x10\x00\x12\n\n\x06WINNER\x10\x01\x12\x08\n\x04TURN\x10\x02\x12\x08\n\x04TIME\x10\x03\x12\x0b\n\x07TIMEOUT\x10\x04\x12\x08\n\x04PORT\x10\x05\x42\x18\n\x05protoB\x0fUdpPacketProtos')
  ,
  dependencies=[player__pb2.DESCRIPTOR,])



_UDPPACKET_PACKETTYPE = _descriptor.EnumDescriptor(
  name='PacketType',
  full_name='UdpPacket.PacketType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DRAW', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WINNER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TURN', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIME', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIMEOUT', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PORT', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=513,
  serialized_end=590,
)
_sym_db.RegisterEnumDescriptor(_UDPPACKET_PACKETTYPE)


_UDPPACKET_DRAWPACKET = _descriptor.Descriptor(
  name='DrawPacket',
  full_name='UdpPacket.DrawPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='UdpPacket.DrawPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='UdpPacket.DrawPacket.x', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='UdpPacket.DrawPacket.y', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color', full_name='UdpPacket.DrawPacket.color', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=171,
)

_UDPPACKET_WINNERPACKET = _descriptor.Descriptor(
  name='WinnerPacket',
  full_name='UdpPacket.WinnerPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='UdpPacket.WinnerPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player', full_name='UdpPacket.WinnerPacket.player', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=249,
)

_UDPPACKET_TIMEOUTPACKET = _descriptor.Descriptor(
  name='TimeoutPacket',
  full_name='UdpPacket.TimeoutPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='UdpPacket.TimeoutPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=303,
)

_UDPPACKET_TURNPACKET = _descriptor.Descriptor(
  name='TurnPacket',
  full_name='UdpPacket.TurnPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='UdpPacket.TurnPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player', full_name='UdpPacket.TurnPacket.player', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='object', full_name='UdpPacket.TurnPacket.object', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=395,
)

_UDPPACKET_TIMEPACKET = _descriptor.Descriptor(
  name='TimePacket',
  full_name='UdpPacket.TimePacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='UdpPacket.TimePacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='UdpPacket.TimePacket.time', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=460,
)

_UDPPACKET_PORTPACKET = _descriptor.Descriptor(
  name='PortPacket',
  full_name='UdpPacket.PortPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='UdpPacket.PortPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=511,
)

_UDPPACKET = _descriptor.Descriptor(
  name='UdpPacket',
  full_name='UdpPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='UdpPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_UDPPACKET_DRAWPACKET, _UDPPACKET_WINNERPACKET, _UDPPACKET_TIMEOUTPACKET, _UDPPACKET_TURNPACKET, _UDPPACKET_TIMEPACKET, _UDPPACKET_PORTPACKET, ],
  enum_types=[
    _UDPPACKET_PACKETTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=590,
)

_UDPPACKET_DRAWPACKET.fields_by_name['type'].enum_type = _UDPPACKET_PACKETTYPE
_UDPPACKET_DRAWPACKET.containing_type = _UDPPACKET
_UDPPACKET_WINNERPACKET.fields_by_name['type'].enum_type = _UDPPACKET_PACKETTYPE
_UDPPACKET_WINNERPACKET.fields_by_name['player'].message_type = player__pb2._PLAYER
_UDPPACKET_WINNERPACKET.containing_type = _UDPPACKET
_UDPPACKET_TIMEOUTPACKET.fields_by_name['type'].enum_type = _UDPPACKET_PACKETTYPE
_UDPPACKET_TIMEOUTPACKET.containing_type = _UDPPACKET
_UDPPACKET_TURNPACKET.fields_by_name['type'].enum_type = _UDPPACKET_PACKETTYPE
_UDPPACKET_TURNPACKET.fields_by_name['player'].message_type = player__pb2._PLAYER
_UDPPACKET_TURNPACKET.containing_type = _UDPPACKET
_UDPPACKET_TIMEPACKET.fields_by_name['type'].enum_type = _UDPPACKET_PACKETTYPE
_UDPPACKET_TIMEPACKET.containing_type = _UDPPACKET
_UDPPACKET_PORTPACKET.fields_by_name['type'].enum_type = _UDPPACKET_PACKETTYPE
_UDPPACKET_PORTPACKET.containing_type = _UDPPACKET
_UDPPACKET.fields_by_name['type'].enum_type = _UDPPACKET_PACKETTYPE
_UDPPACKET_PACKETTYPE.containing_type = _UDPPACKET
DESCRIPTOR.message_types_by_name['UdpPacket'] = _UDPPACKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UdpPacket = _reflection.GeneratedProtocolMessageType('UdpPacket', (_message.Message,), dict(

  DrawPacket = _reflection.GeneratedProtocolMessageType('DrawPacket', (_message.Message,), dict(
    DESCRIPTOR = _UDPPACKET_DRAWPACKET,
    __module__ = 'udp_packet_pb2'
    # @@protoc_insertion_point(class_scope:UdpPacket.DrawPacket)
    ))
  ,

  WinnerPacket = _reflection.GeneratedProtocolMessageType('WinnerPacket', (_message.Message,), dict(
    DESCRIPTOR = _UDPPACKET_WINNERPACKET,
    __module__ = 'udp_packet_pb2'
    # @@protoc_insertion_point(class_scope:UdpPacket.WinnerPacket)
    ))
  ,

  TimeoutPacket = _reflection.GeneratedProtocolMessageType('TimeoutPacket', (_message.Message,), dict(
    DESCRIPTOR = _UDPPACKET_TIMEOUTPACKET,
    __module__ = 'udp_packet_pb2'
    # @@protoc_insertion_point(class_scope:UdpPacket.TimeoutPacket)
    ))
  ,

  TurnPacket = _reflection.GeneratedProtocolMessageType('TurnPacket', (_message.Message,), dict(
    DESCRIPTOR = _UDPPACKET_TURNPACKET,
    __module__ = 'udp_packet_pb2'
    # @@protoc_insertion_point(class_scope:UdpPacket.TurnPacket)
    ))
  ,

  TimePacket = _reflection.GeneratedProtocolMessageType('TimePacket', (_message.Message,), dict(
    DESCRIPTOR = _UDPPACKET_TIMEPACKET,
    __module__ = 'udp_packet_pb2'
    # @@protoc_insertion_point(class_scope:UdpPacket.TimePacket)
    ))
  ,

  PortPacket = _reflection.GeneratedProtocolMessageType('PortPacket', (_message.Message,), dict(
    DESCRIPTOR = _UDPPACKET_PORTPACKET,
    __module__ = 'udp_packet_pb2'
    # @@protoc_insertion_point(class_scope:UdpPacket.PortPacket)
    ))
  ,
  DESCRIPTOR = _UDPPACKET,
  __module__ = 'udp_packet_pb2'
  # @@protoc_insertion_point(class_scope:UdpPacket)
  ))
_sym_db.RegisterMessage(UdpPacket)
_sym_db.RegisterMessage(UdpPacket.DrawPacket)
_sym_db.RegisterMessage(UdpPacket.WinnerPacket)
_sym_db.RegisterMessage(UdpPacket.TimeoutPacket)
_sym_db.RegisterMessage(UdpPacket.TurnPacket)
_sym_db.RegisterMessage(UdpPacket.TimePacket)
_sym_db.RegisterMessage(UdpPacket.PortPacket)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
